spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payorder
  data:
    mongodb:
      uri: mongodb://root:1234@localhost/order?authSource=admin

server:
  port: 8081

service:
  scheme: http
  user:
    port: 8080
    host: localhost
