spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payorder
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            use:
              type:
                headers: 'false'
            trusted:
              packages: '*'
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    mongodb:
      uri: mongodb://root:1234@localhost/order?authSource=admin

server:
  port: 8082

service:
  scheme: http
  user:
    port: 8080
    host: localhost

