spring:
  kafka:
    consumer:
      group-id: payorder
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            use:
              type:
                headers: 'false'
            trusted:
              packages: '*'
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      bootstrap-servers: localhost:29092
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    mongodb:
      host: localhost
      port: 27017
      database: pay

server:
  port: 8081

service:
  scheme: http
  user:
    port: 8080
    host: localhost
