spring:
  main:
    allow-circular-references: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payorder
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            use:
              type:
                headers: 'false'
            trusted:
              packages: '*'
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      retries: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      ack-mode: manual
      poll-timeout: 5000

  data:
    mongodb:
      host: localhost
      port: 27017
      database: pay

server:
  port: 8081

service:
  scheme: http
  user:
    port: 8080
    host: localhost
