spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payorder
  data:
    mongodb:
      host: localhost
      port: 27017
      database: pay

server:
  port: 8081

service:
  scheme: http
  user:
    port: 8080
    host: localhost
